name: docker
on: [push]

jobs:
    docker-job: 
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
            env:
                API_URL: some-url.com
        steps:
            - name: Log Node & OS Versions
              run: 
                node -v
                cat /etc/os-release
            - name: Container in a step 
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /isr/local/bin/node
                #args are used in placed of a command in docker
                args: -p 2+3
