
name: RepoEvents
on: [push,pull_request]

jobs:
    checkout-test:
        runs-on: macos-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3 