
name: RepoEvents
on: 
    pull_request:
        types: [opened,closed]

jobs:
    checkout-test:
        runs-on: macos-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3